### ISSUE TITLE
Add helper to discover matcher for a type

### ISSUE THREAD

**Issue by dchelimsky** [nubank/matcher-combinators#110] opened 2020-03-24 01:01 UTC
This came up in training when I was explaining that types are bound to default matchers, and it takes a bit of digging to understand which matcher is bound to which type. Something like this might help:

```clojure
(matcher-for {:this :map})
;; => (matchers/embeds {:this :map})

(matcher-for 37)
;; => (matchers/equals 37)
```

Don't know if this is feasible, but it's certainly interesting!

**Comment by fernando-nubank** [comment] 2020-05-20 13:16
The "resolution" of the matcher for a common type is made in [parser namespace](https://github.com/nubank/matcher-combinators/blob/master/src/cljc/matcher_combinators/parser.cljc).
The problem is that we only resolve while matching against a value... one idea would be adding another method to the Match protocol, but this seems like a huge change.

**Comment by philomates** [comment] 2020-05-20 13:21
one could annotate the results of a match with metadata regarding the matcher used and then grab that and print it. You would need to change matcher definitions to (optionally) include this information some how, but it could be something that is incrementally added

**Comment by philomates** [comment] 2020-05-20 13:21
cool idea btw!

**Comment by fernando-nubank** [comment] 2020-05-20 13:30
Something like 
```clojure
(matcher-used (match? {:a :map} {})) ;=> (matchers/embeds {:a :map})
```
and `matcher-used` will get this info from `meta`

**Comment by philomates** [comment] 2020-05-20 13:33
I roughly had this in my head, though who knows how it would play out

```clojure
(defn matcher-used [thing]
  (-> thing (match? nil) meta :matcher-used))
```

**Comment by philomates** [comment] 2020-06-04 08:35
addressed in https://github.com/nubank/matcher-combinators/pull/123

**Closed by philomates** 2020-06-04 08:35 UTC
