### ISSUE TITLE
cljs-test integration hack conflicting with tools.namespace refresh

### ISSUE THREAD

**Issue by rafaeldff** [nubank/matcher-combinators#95] opened 2020-01-07 14:36 UTC
If we add matcher-combinators as source dependency of a pure clojure project (e.g. via deps `:local/root`), and try to call `clojure.tools.namespace/refresh`, it will try to load the namespace `matcher-combinators.cljs-test`, which requires `cljs.test`, leading to an error.

**Comment by vemv** [comment] 2020-02-12 02:22
In the described scenario, what are your `clojure.tools.namespace.repl/refresh-dirs`?

Generally it's good to explicitly set them. Maybe if they're not, you'll give `clojure.tools.namespace.repl/refresh` a greater workload than strictly necessary.

Hope it helps!

**Comment by philomates** [comment] 2023-02-08 16:28
I can confirm that this issue comes up with `:local/root` usage. Now with `midje` because the dependency got removed when moving to `deps.edn`.
setting `clojure.tools.namespace.repl/refresh-dirs` to the current project works to avoid this. I think this is the way to go, thanks for the suggestion @vemv

**Closed by philomates** 2023-02-08 16:28 UTC
